version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    volumes:
      - '.:/app:rw,delegated'

  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    volumes:
      - './public:/app/public'
    ports:
      - '80:80'
    depends_on:
      - app

  queue:
    image: rabbitmq:3.7

  batch:
    image: symfony-messenger-test_app
    command: ['bin/console', 'messenger:consume-messages', 'amqp']
    init: true
    stop_signal: SIGTERM
    volumes:
      - '.:/app:rw,delegated'
    depends_on:
      - queue
