version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile

    volumes:
      - '.:/var/www/html:rw,cached'
  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    volumes:
      - './public:/var/www/html/public'
    ports:
      - '80:80'
    depends_on:
      - app
