version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
      target: app-develop-fpm
    volumes:
      - '.:/app:rw,delegated'

  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    volumes:
      - './public:/app/public'
    ports:
      - '80:80'
    depends_on:
      - app

  queue:
    image: rabbitmq:3.7

  batch:
    build:
      context: .
      dockerfile: docker/app.dockerfile
      target: app-develop
    command: ['bin/console', 'messenger:consume-messages', 'amqp']
    init: true
    volumes:
      - '.:/app:rw,delegated'
    depends_on:
      - queue
