version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    volumes:
      - '.:/app:rw,delegated'

  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    volumes:
      - './public:/app/public'
    ports:
      - '80:80'
    depends_on:
      - app

volumes:
  app_public:
